# Generated by Django 5.1.7 on 2025-04-18 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0009_alter_threatlog_ai_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlog',
            name='ai_risk_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='confidence_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]

# maintenance 2025-09-06
