# Generated by Django 5.1.7 on 2025-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0010_alter_threatlog_ai_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
