# Generated by Django 5.1.7 on 2025-04-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0011_threatlog_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatlog',
            name='details',
        ),
    ]
