# Generated by Django 5.1.7 on 2025-04-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0012_remove_threatlog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='destination_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='source_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
