# Generated by Django 5.1.7 on 2025-04-16 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarkWebAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('credentials_leak', 'Credentials Leak'), ('ip_exposure', 'IP Exposure'), ('malware_market', 'Malware Market')], max_length=50)),
                ('affected_data', models.TextField(help_text='Leaked credentials, IPs, or other sensitive data.')),
                ('source', models.CharField(help_text='Source of leak or breach.', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
            ],
        ),
    ]
