# Generated by Django 5.1.7 on 2025-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web_monitoring', '0002_remove_darkwebalert_affected_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darkwebalert',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Dark Web Alert', 'verbose_name_plural': 'Dark Web Alerts'},
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='affected_domain',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='affected_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='confidence_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='threat_type',
            field=models.CharField(choices=[('data_breach', 'Data Breach'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('ransomware', 'Ransomware'), ('exploit', 'Exploit'), ('credentials', 'Stolen Credentials'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='verification_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
