# Generated by Django 5.1.7 on 2025-04-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='ip_category',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='risk_level',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
