# Generated by Django 5.1.7 on 2025-04-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_threatlog_details_threatlog_ip_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='ip_category',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='threatlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
