# Generated by Django 5.1.7 on 2025-04-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_threatlog_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_ads', models.BooleanField(default=False)),
                ('has_malware', models.BooleanField(default=False)),
                ('has_phishing', models.BooleanField(default=False)),
                ('has_redirects', models.BooleanField(default=False)),
                ('redirect_chain', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('threat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.threatcategory')),
            ],
        ),
    ]
